spring:
  application:
    name=eureka-server

server:
  port: 9099
eureka:
  instance:
    prefer-ip-address=true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9099/eureka